In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('weight-height.csv')
df.head()
df.shape

(10000, 3)

In [3]:
df.isnull().values.any()

False

In [4]:
df[df['Gender']=="Male"].shape

(5000, 3)

In [5]:
df.groupby('Gender').mean()

Kilo         Boy
Gender                       
Female  63.708774  135.860093
Male    69.026346  187.020621

In [6]:
df["Gender"].replace("Male",0,inplace=True)
df["Gender"].replace("Female",1,inplace=True)

df.tail()

Gender       Kilo         Boy
9995       1  66.172652  136.777454
9996       1  67.067155  170.867906
9997       1  63.867992  128.475319
9998       1  69.034243  163.852461
9999       1  61.944246  113.649103

In [7]:
X=df[['Kilo','Boy']]
y=df['Gender']

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20, random_state=1)

from sklearn import linear_model

lg=linear_model.LogisticRegression()

model=lg.fit(X_train,y_train)

In [9]:
model.coef_

array([[ 0.47718981, -0.19613768]])

In [11]:
model.intercept_

array([0.00998774])

In [13]:
print(lg.score(X_test,y_test))

0.913


In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
pred=model.predict(X_test)

In [24]:
pred.shape

(2000,)

In [17]:
confusion_matrix(y_test,pred)

array([[927,  94],
       [ 80, 899]], dtype=int64)

In [18]:
(927+899)/2000

0.913

In [21]:
print("Sensitivity:",(899/(899+80)))

Sensitivity: 0.9182839632277835


In [23]:
from sklearn.metrics import recall_score
print (recall_score(y_test,pred))

0.9182839632277835


In [33]:
model.predict([[70,190]])

array([0], dtype=int64)

In [22]:
from sklearn.metrics import classification_report
print (classification_report(y_test,pred,digits=4))

              precision    recall  f1-score   support

           0     0.9206    0.9079    0.9142      1021
           1     0.9053    0.9183    0.9118       979

    accuracy                         0.9130      2000
   macro avg     0.9129    0.9131    0.9130      2000
weighted avg     0.9131    0.9130    0.9130      2000

